[package]
name = "vinegar"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.22.1"
rand = "0.9.1"
clap = { version = "4.0", features = ["derive"] }
wasm-bindgen = "0.2.100"
getrandom = { version = "0.3", features = ["wasm_js"] }
